name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: make validate

      - name: Install project
        run: make install

      - name: Run linter
        run: make lint
